src/components/TimeSeriesChart.tsx
src/config.ts

When you accept, you get 
* adjusted theme-dependent line colors so they have a little more contrast;
* some tiny code optimisations.

Adjusted line colors and tiny optimisations.

---

src/components/Viewer.tsx
src/model/dataset.ts

When accepting this PR the Viewer will:
- Zoom to gemoentroies when selected from the Place Selection even if the second place group is selected.
- If the geoemtry is a point it zooms to an extent of 1km/0.01dfeg around that point.

Fixes issue #52: Zooming Issue on Selecting Places

---

CHANGELOG.md
src/actions/controlActions.tsx
src/actions/dataActions.tsx
src/api/getDatasetPlaceGroup.ts
src/api/index.js
src/model/dataset.ts
src/model/place.ts
src/reducers/dataReducer.ts
src/selectors/controlSelectors.tsx

Closes #61 
Don't merge before https://github.com/dcs4cop/xcube/pull/131

Lazy-load place group feature collections

---

CHANGELOG.md
src/components/AppMenu.tsx
src/connected/AppBar.tsx

Commented out dummy app bar icons ("Notifications", "Avatar") and menu entry ("Settings...").
Once we really implement them, we can reactivate code.

removed dummy UI

---

CHANGES.md
package.json
src/components/LegalAgreementDialog.tsx
src/connected/App.tsx
src/connected/LegalAgreementDialog.tsx
src/resources/lang.json
src/states/controlState.ts
src/states/userSettings.ts
yarn.lock

Forman 77 legal agreement

---

CHANGES.md
src/components/ol/Map.tsx

Restrict zooming out, so that only a single world is shown.

---

src/components/Viewer.tsx
src/components/ol/Map.tsx
src/components/ol/control/Control.tsx

Forman 81 dont zoom out

---

src/components/TimeSeriesChart.tsx
src/components/Viewer.tsx
src/components/ol/Map.tsx
src/components/ol/interaction/Draw.tsx
src/components/ol/interaction/Select.tsx
src/connected/Viewer.tsx
src/model/place.ts
src/selectors/controlSelectors.tsx

@AliceBalfanz and @dzelge There is no related issue as all of the issues fixed are related to new, buggy features - they are regressions. Please verify that this PR does the following:

Forman fix colors

---

CHANGES.md
src/api/callApi.ts
src/components/ol/control/Control.tsx
src/states/controlState.ts

* Fixed (actually avoided) problem indicated by text "something went wrong" appearing instead of map after server change. 
* Changed user setting "show graph after adding point" to be on by default.
* Added translations for message "server did not respond".
As always, I'll update cyanoalert and dcs4cop branches after approval, @Helge can you then pls upd ESDL viewer.

Forman some new fixes

---

CHANGES.md
README.md
src/actions/dataActions.tsx
src/api/getServerInfo.ts
src/api/index.js
src/components/SettingsDialog.tsx
src/config.ts
src/connected/SettingsDialog.tsx
src/index.tsx
src/model/server.ts
src/reducers/dataReducer.ts
src/resources/lang.json
src/states/dataState.ts

Show system info in settings dialog. This is the last PR before 0.2 release.

Forman 93 show system info

---

CHANGES.md
package.json
src/config.ts
src/resources/lang.json

Releasing 0.3.1 with translated legal agreement.

releasing 0.3.1

---

src/resources/lang.json

Adjusting Italian translation, based on feedback of users.

update of italian translation

---

CHANGES.md
src/components/UserControl.tsx
src/connected/AppBar.tsx
src/connected/AppPane.tsx

Some UI cosmetics suggested by Susanne Thulin:
* Made the app bar a little more dense (48 instead of 56px).
* Using more intuitive icons for user login and settings.

Some UI cosmetics

---

CHANGES.md
public/manual.md
src/components/ColorBarLegend.tsx
src/components/ControlBarActions.tsx
src/components/InfoCard.tsx
src/components/MapInteractionsBar.tsx
src/components/MarkdownPage.tsx
src/components/PlaceGroupsSelect.tsx
src/components/PlaceSelect.tsx
src/components/RgbSwitch.tsx
src/components/TimePlayer.tsx
src/components/TimeRangeSlider.tsx
src/components/TimeSelect.tsx
src/components/TimeSeriesChart.tsx
src/components/TimeSlider.tsx
src/components/VariableSelect.tsx
src/connected/AppBar.tsx
src/resources/lang.json
src/util/time.ts

* Date/time displayed in the date/time select field and displayed in time-series plots are now aligned. Both use Coordinated Universal Time (UTC) and ISO format (#133).  
* Attached tooltips to many prominent viewer functions.
* Added link into xcube viewer RTD pages
@AliceBalfanz please merge once you are happy with the PR.

Forman xxx final issues v05

---

CHANGES.md
src/index.tsx
src/reducers/controlReducer.ts
src/states/userSettings.ts

fixes #158

---

src/actions/controlActions.tsx
src/actions/dataActions.tsx
src/components/ControlBarActions.tsx
src/components/ExportDialog.tsx
src/components/SettingsDialog.tsx
src/components/SettingsPanel.tsx
src/components/SettingsSubPanel.tsx
src/components/ToggleSetting.tsx
src/config.ts
src/connected/AppBar.tsx
src/connected/ExportDialog.tsx
src/model/timeSeries.ts
src/reducers/controlReducer.ts
src/resources/lang.json
src/states/controlState.ts
src/states/userSettings.ts

Download Time-Series Data v2

---

CHANGES.md
src/components/ColorBarLegend.tsx

Manually entering color bar min/max

---

.github/workflows/xcube-viewer_workflow.yaml

When accepting this PR the workflow should run again

Dzelge xxx gh actions

---

.github/workflows/xcube-viewer-workflow.yaml

Tiny PR, renaming in workflow to minimise confusion :)

minor renaming change - to minimise confusion

---

CHANGES.md
src/reducers/dataReducer.ts

Update all datasets referring to the same place group on feature reload

---

CHANGES.md
src/components/TimePlayer.tsx
src/components/TimeSelect.tsx
src/components/TimeSlider.tsx
src/connected/TimeSelect.tsx
src/connected/TimeSlider.tsx
src/model/dataset.ts
src/resources/lang.json

This PR allows displaying also 2D datasets such as opened from GeoTIFF / COG files.
**IMPORTANT:** Requires https://github.com/dcs4cop/xcube/pull/689

Display 2D datasets

---

src/components/ControlBar.tsx
src/components/SplitPane.tsx
src/components/Splitter.tsx
src/components/Viewer.tsx
src/components/ol/Map.tsx
src/connected/App.tsx
src/connected/AppPane.tsx
src/connected/Viewer.tsx
src/connected/Workspace.tsx
src/index.css

Added a drag bar between map view and details panel so users can set the width/height of the map for horizontal/vertical window sizes.
Closes #242

Allow resizing of map with opened details panel

---

CHANGES.md
src/components/ol/View.tsx

Transform features on CRS change

---

CHANGES.md
src/config.ts
src/resources/config.json
src/resources/config.schema.json
src/util/branding.ts

Window title and favicon can now be configured

---

public/imprint.md
public/legal/privacy-note.de.md
public/legal/privacy-note.en.md
public/legal/privacy-note.it.md
public/legal/privacy-note.ro.md
public/legal/privacy-note.se.md
src/actions/dataActions.tsx
src/components/LegalAgreementDialog.tsx
src/components/MarkdownPage.tsx
src/components/SettingsDialog.tsx
src/connected/App.tsx
src/connected/AppPane.tsx
src/connected/ControlBar.tsx
src/connected/LegalAgreementDialog.tsx
src/connected/Workspace.tsx
src/index.tsx
src/resources/lang.json
src/states/controlState.ts
src/states/userSettings.ts

Verify this screen is shown:
Accept and continue --> ok
Leave --> navigate back, if not possible, navigate home, if not possible, reload page
Revoke consent

Updated privacy notice

---

CHANGES.md
package.json
src/components/UserControl.tsx
src/version.ts

Fix user profile crash

---

CHANGES.md
package.json
src/actions/dataActions.tsx
src/components/TimeSeriesChart.tsx
src/components/TimeSeriesCharts.tsx
src/connected/TimeSeriesCharts.tsx
src/reducers/dataReducer.ts

Remove individual timeseries from a chart

---

CHANGES.md
src/components/TimeSelect.tsx
src/util/time.ts

Times are now correctly displayed using standard UTC timezone in ISO format. 
Closes #281

Force UTC time display

---

CHANGES.md
src/config.ts

This PR is for issue  https://github.com/dcs4cop/xcube-viewer/issues/299

Viewer crashing after 10 points plotting issue resolved

---

public/imprint.md

Adjusted imprint based on existing imprint and https://agriculturevlab.eu/index.php/imprint/
Please note, that google fonts are not fetched from google servers anymore (https://github.com/dcs4cop/xcube-viewer/pull/295).
@okhamrai somehow I cannot make you a reviewer. But maybe you can still see the changes?

Adjusting Imprint text

---

src/components/VariableSelect.tsx
src/reducers/controlReducer.ts

Selecting 2nd variable also switches on compare mode.

Automatically switch compare mode

---

src/components/ColorBarLegend/UserColorBarGroup.tsx
src/components/LayerSelect/LayerSelect.tsx
src/components/MapInteractionsBar.tsx
src/components/TimePlayer.tsx
src/components/TimeSelect.tsx
src/components/VariableSelect.tsx
src/components/common-styles.ts

Harmonized `ToggleButton` styles.
FYI @ruchimotwaniBC

Harmonized styles

---

src/actions/controlActions.tsx
src/components/MapSplitter.tsx
src/components/SplitPane.tsx
src/components/Splitter.tsx
src/connected/Workspace.tsx
src/hooks/useMouseDrag.ts
src/reducers/controlReducer.ts
src/states/controlState.ts

Remember last sidebar split position

---

src/components/TimeSeriesPanel/NoTimeSeriesChart.tsx
src/components/TimeSeriesPanel/TimeSeriesPanel.tsx
src/components/VariableSelect.tsx
src/connected/TimeSeriesPanel.tsx

Show `NoTimeSeriesChart` component if no time-series have been created yet.
FYI @ruchimotwaniBC

Handle case where no time-series have been created yet

---

src/api/callApi.ts
src/api/getColorBars.ts
src/api/getDatasets.ts
src/api/getTimeSeries.ts
src/hooks/usePromise.ts

Simplifying API calls

---

public/docs/add-layer-wms.de.md
public/docs/add-layer-wms.se.md
public/docs/add-layer-xyz.de.md
public/docs/add-layer-xyz.se.md
public/docs/color-mappings.de.md
public/docs/color-mappings.se.md
src/components/ColorBarLegend/UserColorBarEditor.tsx
src/components/ColorBarLegend/UserColorBarGroup.tsx
src/components/UserLayersDialog/UserLayerEditorWms.tsx
src/components/UserLayersDialog/UserLayerEditorXyz.tsx
src/components/VolumePanel/VolumeCanvas.tsx
src/resources/lang.json

This pull request updates the translation from english to german and swedish.

Updated translation

---

CHANGES.md
src/components/StatisticsPanel/HistogramChart.tsx

When trying to load statistic, viewer breakdown issue solved

---

public/docs/add-layer-wms.de.md
public/docs/add-layer-xyz.de.md
public/docs/user-variables.de.md
public/docs/user-variables.en.md
public/docs/user-variables.se.md
src/components/UserVariablesDialog/UserVariableEditor.tsx
src/components/VariableSelect.tsx
src/resources/lang.json

Content of this PR:
- updated translations (epecially help text in User Variable Dialog)
- added tooltips (regarding User Variables) for an improved usability

Updated translation and added tooltips

---

CHANGES.md
src/actions/controlActions.tsx

Fixed map behaviour after selecting dataset or place

---

CHANGES.md
src/components/ColorBarLegend/ColorBarLegendCategorical.tsx
src/model/userColorBar.ts

Fix categorical map legend

---

CHANGES.md
src/components/DatasetSelect.tsx
src/model/dataset.ts

Closes #385
Requires https://github.com/xcube-dev/xcube/pull/1039

Grouping and sorting datasets

---

CHANGES.md
src/actions/dataActions.tsx
src/components/Viewer.tsx
src/connected/ColorBarLegend2.tsx
src/connected/Viewer.tsx
src/selectors/controlSelectors.tsx

When in map split mode each of the two variables has its own color legend with same functionality.
Closes #401

Introducing 2nd color legend in split mode

---

CHANGES.md
src/components/ColorBarLegend/ColorBarLegend.tsx

Long variable titles now wrap at words in color legend

---

CHANGES.md
src/api/getColorBars.ts
src/components/ColorBarLegend/ColorBarLegendCategorical.tsx
src/components/ColorBarLegend/ColorMapTypeEditor.tsx
src/components/ColorBarLegend/UserColorBarEditor.tsx
src/model/colorBar.ts
src/model/userColorBar.ts
src/selectors/controlSelectors.tsx
src/states/userSettings.ts

Closes #392
Requires https://github.com/xcube-dev/xcube/pull/1057

Recognising new custom color maps from xcube server

---

src/components/TimePlayer.tsx
src/resources/lang.json

This PR:
- adds tooltips and translations regarding the Time Player
- adds some missed translations

Add tooltips for Time Player

---

docs/features.md

this PR holds:
- modified paths for correct image display

correct image display

---

docs/features.md

PR includes:
- fixed links in features.md

Fix links in docs

---

package-lock.json
package.json
src/components/ImprintPage.tsx
src/ext/actions.ts

Add plugins in initializeContributions
Also fixes the build error that we get from the `ImprintPage.tsx`

Fix Chartlets v0.1.0 integration with xcube-viewer

---

CHANGES.md
package-lock.json
package.json
src/connected/AppBar.tsx
src/version.ts

Fix share feature

---

CHANGES.md
package-lock.json
package.json
src/components/ColorBarLegend/ColorBarLegend.tsx
src/connected/ColorBarLegend.tsx
src/connected/ColorBarLegend2.tsx
src/selectors/controlSelectors.tsx
src/version.ts

Display dataset titles in the map legend

---

CHANGES.md
src/components/TimeSeriesPanel/TimeSeriesChart.tsx

Fixed regression when zooming into time-series charts

---

CHANGES.md
src/components/ColorBarLegend/ColorBarCanvas.tsx
src/components/ColorBarLegend/ColorBarItem.tsx
src/components/ColorBarLegend/ColorBarLabels.tsx
src/components/ColorBarLegend/ColorBarLegend.tsx
src/components/ColorBarLegend/style.ts

Variable layer legends are now styled according to the current theme mode.
Closes #491

Style legend wrt theme mode

---

CHANGES.md
src/components/SidePanel/SidePanel.tsx
src/components/SidePanel/SidePanelContent.tsx
src/components/SidePanel/SidePanelHeader.tsx
src/components/SidePanel/panelModel.ts
src/connected/SidePanel.tsx

Fixed the problem where a server-side side panel was not rendered after app start, if it was the initially selected one.
Closes #476

Fixed the problem where a server-side side panel was not rendered

---

vite.config.ts

This PR updates the vite config `vite.config.ts` to fix css issues that occur when using npm link to use the `chartlets` package locally for development and testing purposes

Update vite config
