src/components/TimeSeriesChart.tsx
when accepting this PR the color fpr the toime chart axis labels will now be set by pallette.primary.contrastText.
=> - Changed axis label color to palette.primary.contrastText

CHANGELOG.md, src/actions/dataActions.tsx
When accepting this PR the viewer will then load when using the MS EWdge Browser which solves #59.
=> Fixes issue #59: The viewer should load now in the MS Edge browser

CHANGELOG.md, src/components/PlaceGroupsSelect.tsx, src/components/PlaceSelect.tsx
* Place groups dropdown menus are no longer displayed if a dataset has no place groups and 
* the places dropdown is no longer shown if no place group is selected.
=> empty place groups and places are now hidden from viewer

CHANGES.md, package.json, src/actions/controlActions.tsx, src/actions/dataActions.tsx, src/components/ControlBar.tsx, src/components/MapInteractionsBar.tsx, src/components/PlaceSelect.tsx, src/components/TimePlayer.tsx, src/components/TimeSeriesChart.tsx, src/components/TimeSeriesCharts.tsx, src/components/Viewer.test.tsx, src/components/Viewer.tsx, src/components/ol/Map.tsx, src/components/ol/interaction/Draw.tsx, src/components/ol/interaction/Select.tsx, src/components/ol/layer/Tile.tsx, src/connected/ControlBar.tsx, src/connected/MapInteractionsBar.tsx, src/connected/TimeSeriesCharts.tsx, src/connected/Viewer.tsx, src/model/dataset.ts, src/model/place.ts, src/reducers/controlReducer.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/states/controlState.ts, yarn.lock
Note, this PR includes PR #85, check that one first.
In addition:
* Users can now draw polygons and circles and show respective time-series. (#32)
In total there are now 4 new interactions with the map:
- Select a geometry
- Draw a point
- Draw a geometry
- Draw a circle 
* Improved selection of places:
- If a place is selected in the list, it is zoomed to and highlighted in the map;
- Places can now be selected in the map if the "Select" interaction is active;
- Places are also selected if a time-series line is clicked.
(However, that doesn't work nicely yet due to issues in the Recharts lib).
* Minor fixes:
* Colors used for geometries in the map and for lines in the time-series charts are now exactly the same.
* Time-series charts now have constant spacing
Closes #32
=> Forman 32 draw user shapes

CHANGES.md, src/actions/controlActions.tsx, src/components/InfoCard.tsx, src/components/RgbSwitch.tsx, src/components/TimeSeriesModeSelect.tsx, src/components/Viewer.tsx, src/connected/ControlBar.tsx, src/connected/RgbSwitch.tsx, src/connected/Viewer.tsx, src/model/dataset.ts, src/model/tile.ts, src/model/variable.ts, src/reducers/controlReducer.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/states/controlState.ts
* Please first review https://github.com/dcs4cop/xcube/pull/279!
* Added a "RGB" switch to the app bar that is used to display the selected dataset's RGB layer, 
if any. Currently, RGB layers can only be configured through the xcube server. Later xcube viewer 
versions will allow users selecting three variables and their respective value ranges for normalisation.
=> Forman xxx rgb tiles

CHANGES.md, src/actions/dataActions.tsx, src/api/getTimeSeries.ts, src/components/SettingsDialog.tsx, src/components/TimeSeriesChart.tsx, src/config.ts, src/model/timeSeries.ts, src/resources/lang.json, src/states/controlState.ts, src/states/userSettings.ts
Users can now switch between median and mean methods for the spatial aggregation of 
polygons when creating time-series. The setting is available in the settings dialog. 
(partly addresses #135).
* Testing the new function requires xcube branch https://github.com/dcs4cop/xcube/tree/forman-292-ts_agg_methods.
* Please first see PR https://github.com/dcs4cop/xcube/pull/293
=> can now switch between median and mean

src/resources/maps.json
To avoid having the browser requesting clear http traffic for the background maps, I tested which of these maps could be requested over https and modified accordingly:
-All OSM except Landscape
-All ESRI
-All CartoDB
I didn't modify Stamen maps as these fail when https is required.
I didn't modify mapbox maps as I tested on a localhost instance and couldn't give an API key
=> make maps https where possible

.github/workflows/xcube-viewer_workflow.yaml, Dockerfile
When accepting this PR as GH Actions workflow will be added that will:
- run unit tests (can be switched off)
- Build a docker image and push it to quay.io
- Update the docker image version tags in https://github.com/bc-org/k8s-configs
The version tags will be updated according to the deployment stage:
- pushes to master will update dev
- dev releases will updated version tag in the stage and dev phase
- production releases will updated version tag in the prod, stage and dev phase
=> Dzelge xxx gh actions

CHANGES.md, src/connected/AppBar.tsx, src/resources/config.json, src/resources/config.schema.json, src/resources/maps.json, src/util/branding.ts
* The logo in the application's main bar is now a link. The target URL can be configured using the `branding.organisationUrl` key. 
Closes #176
=> logo in the application's main bar is now a link

CHANGES.md, package.json, src/api/getDatasetPlaceGroup.ts, src/api/getTimeSeries.ts, src/version.ts
Fixed issue with datasets originating from nested, filesystem-based data stores such as the "s3" and "file" data stores. See also related https://github.com/dcs4cop/xcube/issues/588.  
Closes #190
=> xcube viewer to support nested datasets

public/config/cyanoalert/config.json, src/resources/maps.json
This PR removes defect basemaps and closes #197 
The reasons are:
- Stamen (all) - does not provide https basemaps
- Mapbox (all) - does not provide the basemaps without registration and token anymore
- OpenStreetMap : 
- OSM Black & White - is not maintained  and provided anymore
- OSM Landscape  - is not accessible without registration
=> removing defect basemaps

CHANGES.md, src/components/Viewer.tsx, src/components/ol/Map.tsx, src/resources/config.json, src/resources/config.schema.json, src/selectors/controlSelectors.tsx, src/util/branding.ts
In this PR:
* Feature geometries loaded from xcube Places API are now rendered again in the map.
* The map projection can now be configured using the `branding.mapProjection` key. Possible values are the default `"EPSG:4326"` (Geographic) and `"EPSG:3857"` (Spherical Mercator).
=> Fixed rendering places, allow for map projection configuration

CHANGES.md, package.json, src/actions/controlActions.tsx, src/actions/dataActions.tsx, src/components/ColorBarLegend.tsx, src/components/Viewer.tsx, src/components/ol/Map.tsx, src/components/ol/View.tsx, src/components/ol/layer/Tile.tsx, src/connected/ColorBarLegend.tsx, src/model/dataset.ts, src/model/variable.ts, src/reducers/dataReducer.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/states/userSettings.ts, yarn.lock
Now the opacity of tile layers can be changed from the color bar dropdown component in the map.
**NOTE**
This PR also fixes two bugs present in the branch [forman-xxx-crs_indepenence](https://github.com/dcs4cop/xcube-viewer/tree/forman-xxx-crs_indepenence):
* fixed flickering (once more)
* fixed bug for undefined "oldTileRange"
=> Added opacity slider (to CRS branch)

CHANGES.md, package.json, src/actions/dataActions.tsx, src/components/InfoCard.tsx, src/components/SettingsDialog.tsx, src/model/variable.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/version.ts
In this PR:
The performance of time-series fetching has been significantly improved by exploiting the actual chunk sizes of the time dimension of a variable.
For this to work, the setting "Number of data points in a time series update" has been replaced by "_Minimal_ number of data points in a time series update". The effective number of data points is now always an integer multiple of the actual variable's time chunk size.
**Important Note**: This PR requires https://github.com/dcs4cop/xcube/pull/675
=> Use dataset time chunks

CHANGES.md, src/components/TimeSeriesChart.tsx
In this PR:
* Fixed a bug that caused the app to crash when zooming into the time-series chart. 
* Text selection has now been disabled for the time-series charts. Zooming in no longer selects the axes' labels.
Closes #163
=> Fix zooming into time-series chart

CHANGES.md, src/components/InfoCard.tsx, src/components/SettingsDialog.tsx, src/components/Viewer.tsx, src/connected/Viewer.tsx, src/model/dataset.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/states/controlState.ts
* In the info panel, the dataset's spatial reference system is shown.
* It is now possible to display dataset boundaries in the map. A new setting "Show dataset boundaries" is available to switch this feature on and off. 
**IMPORTANT:** Requires https://github.com/dcs4cop/xcube/pull/685
Closes #225
Closes #226
=> Show spatial reference & dataset boundaries

CHANGES.md, src/connected/AppBar.tsx, src/resources/config.json, src/util/branding.ts
The style of the title and icons of the app's header bar can now be customized by two new branding properties `` and `` that can provide any CCS attributes (using camel-case attribute names). 
For example
```json
{   
"branding": {
"headerTitleStyle": {
"fontFamily": "courier",
"color": "yellow"
},
"headerIconStyle": {
"color": "black"
},
...
},
...
}
```
Closes #227
=> Improve header styling

CHANGES.md, src/actions/dataActions.tsx, src/api/index.ts, src/api/updateResources.ts, src/connected/AppBar.tsx, src/resources/config.json, src/resources/config.schema.json, src/resources/lang.json, src/util/branding.ts
A new refresh icon in the main bar now allows updating server-side resources and refresh the page. For this to work, the configuration setting  `branding.allowRefresh` must be `true`.
**IMPORTANT:** Requires https://github.com/dcs4cop/xcube/pull/696
=> Update server-side resources and refresh the page

CHANGES.md, src/config.ts, src/selectors/controlSelectors.tsx
Tiles of datasets with forward slashes in their identifiers (originated from nested directories) now display again correctly. Tile URLs have not been URL-encoded in such cases. 
Closes #269.
=> URL-encode Tile URLs

CHANGES.md, src/resources/config.schema.json, src/util/branding.ts
* Values of branding parameters `primaryColor` and `secondaryColor`
can now be arbitrary HTML color hex codes, such as `"#76ff03"`.
They used to be color names only, such as `"red"`.
Adapted `src/recesources/config.schema.json` to reflect the change.
* Fixed `src/recesources/config.schema.json` where invalid item 
`example: string` was used instead of `examples: string[]`.
=> Fix branding parameters `primaryColor` and `secondaryColor`

CHANGES.md, src/components/AuthWrapper.tsx, src/config.ts
* For user login, the default value for the redirect URI 
is now `baseUrl.href` instead of `window.location.origin` 
in order for viewer deployments that make use of new xcube 
server endpoint `"/viewer"` introduced in xcube 1.0.
* Now supporting [dotenv](https://github.com/motdotla/dotenv) 
for testing while developing xcube-viewer.
We support server configuration and auth configuration variables:
```bash
REACT_APP_SERVER_ID=my_server
REACT_APP_SERVER_NAME=My Server
REACT_APP_SERVER_URL=http://127.0.0.1:8181
REACT_APP_OAUTH2_AUTHORITY=https://my.authority.eu
REACT_APP_OAUTH2_CLIENT_ID=kjJKs5n7kj5k7fo9l3
REACT_APP_OAUTH2_AUDIENCE=https://my.audience.eu/api/
```
=> Use baseUrl.href instead of window.location.origin.

CHANGES.md, public/manual.md, src/connected/AppBar.tsx
Inlined the help menu into the app bar. The help icon button now opens the [xcube Viewer documentation](https://xcube.readthedocs.io/en/latest/viewer.html) in a new browser tab.
=> Inline help menu

CHANGES.md, src/connected/Workspace.tsx, src/index.css
This error was encountered when we are trying to resize the browser window or even open the developer options.
To resolve this error, I have written a workaround to catch this error and then hiding the element. Since this error doesn't break our current/running workflow this solution is quite reasonable. 
We can make changes in future if we find a better solution than this. 
Please refer below links I found and used for workaround for this issue :
https://stackoverflow.com/questions/75774800/how-to-stop-resizeobserver-loop-limit-exceeded-error-from-appearing-in-react-a
https://gitlab.com/gitlab-org/gitlab-ui/-/issues/2233
=> Window crashing on resizing issue resolved

CHANGES.md, src/actions/dataActions.tsx, src/api/getTimeSeries.ts, src/components/SettingsDialog.tsx, src/components/TimeSeriesCharts/TimeSeriesChart.tsx, src/components/TimeSeriesCharts/TimeSeriesChartHeader.tsx, src/components/TimeSeriesCharts/TimeSeriesCharts.tsx, src/components/TimeSeriesCharts/TimeSeriesLine.tsx, src/connected/TimeSeriesCharts.tsx, src/resources/lang.json, src/states/controlState.ts, src/states/userSettings.ts
Users can now change the chart type (point, line, bars) and toggle showing standard deviation directly from the time-series chart's action bar.
=> Change chart type (point, line, bars) and toggle showing standard deviation

CHANGES.md, src/components/TimeSeriesPanel/TimeSeriesChart.tsx
Fixed a problem where a date in the time-series chart could not be selected if clicked next to a data point. 
Closes #381
=> Fixed date in time-series chart selection

CHANGES.md, src/actions/dataActions.tsx, src/actions/mapActions.tsx, src/components/PlaceSelect.tsx, src/components/PlaceStyleEditor/PlaceStyleEditor.tsx, src/components/PlaceStyleEditor/index.tsx, src/components/UserVectorLayer.tsx, src/components/Viewer.tsx, src/components/ol/style.ts, src/config.ts, src/connected/PlaceSelect.tsx, src/connected/StatisticsPanel.tsx, src/model/place.ts, src/reducers/dataReducer.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx, src/selectors/dataSelectors.tsx
We can now change color and opacity of user drawn points and shapes. Also, improved visual style of selected places in the map.
Closes #216
Closes #97 
To verify:
- Draw several polygon places
- Create timeseries and statistics for them
- Next to the place selector find the new style editor
- Change color and opacity --> shape should change style accordingly
- See also the colors of timeseries and statistics changing
- Test for points too
=> Change color and opacity of user places

CHANGES.md, src/components/ColorBarLegend/ColorBarLabels.tsx, src/components/ColorBarLegend/ColorBarLegend.tsx, src/components/ColorBarLegend/ColorBarLegendCategorical.tsx, src/components/ColorBarLegend/ColorBarLegendContinuous.tsx, src/components/ColorBarLegend/ColorBarLegendScalable.tsx, src/components/ColorBarLegend/ColorBarRangeEditor.tsx, src/components/ColorBarLegend/ColorBarStyleEditor.tsx, src/components/ColorBarLegend/ColorMapTypeEditor.tsx, src/components/ToolButton.tsx, src/connected/ColorBarLegend.tsx, src/model/colorBar.ts, src/model/variable.ts, src/resources/lang.json, src/selectors/controlSelectors.tsx
Revised map color mapping for simplicity and clarity:
- Removed the color mapping normalisation modes. Instead introduced a "Log" switch in the value-range popup. The normalisation mode "CAT" (categorical) is no longer required.
- Renamed the user color mapping types "Node", "Bound", "Key" into "Cont." (continuous), "Stepwise", and "Categ." (categorical).
- The color legend is now showing the variable's UI title instead of the variable identifier name.
Requires https://github.com/xcube-dev/xcube/pull/1044
Closes #390
To verify use the demo server setup, then in the UI
- create three new color bars: continuous, stepwise, categorical each with 3 values: 0, 1, 2
- apply each to conc_chl and watch the colors in the map chaning 
- apply each to chl_category and watch the legend changing if the …
=> Revise new color bar features

CHANGES.md, src/components/ColorBarLegend/ColorBarLegend.tsx, src/components/ColorBarLegend/ColorMapTypeEditor.tsx, src/model/userColorBar.test.ts, src/model/userColorBar.ts, src/reducers/controlReducer.ts, src/resources/lang.json, src/states/userSettings.ts, src/util/storage.ts
- Renamed internal color mapping types from `"node"`, `"bound"`, `"key"` into `"continuous"`, `"stepwise"`, `"categorical"`.
- Adjusted tooltip texts.
Requires https://github.com/xcube-dev/xcube/pull/1049
=> Renamed internal color mapping types

public/docs/color-mappings.de.md, public/docs/color-mappings.en.md, public/docs/color-mappings.se.md, src/resources/lang.json
This PR:
- updates the help text for the simplified color mapping
- fixes a small typo.
=> Update help text for color mapping

CHANGES.md, src/components/ol/layer/common.ts, src/selectors/controlSelectors.tsx
Map layers that represent dataset variable's will no longer request tiles for regions that do not intersect with the dataset's extent. This improves both viewer and server performance. 
Closes #412
=> Use tile layer extent

CHANGES.md, src/actions/dataActions.tsx, src/api/getStatistics.ts, src/components/StatisticsPanel/StatisticsRow.tsx, src/model/statistics.ts, src/selectors/controlSelectors.tsx
This PR removes the time dimension to be required for calculating the stats for datasets that do not have a time dimension making the time optional. It also toggles the missing `<Time?>` based on the availability of that dimension
Closes #421
=> Make time dimension optional for Statistics panel

CHANGES.md, README.md, src/connected/AppBar.tsx
This PR is to replace old URLs with the new user guide link for the xcube viewer user guide.
=> Read the docs link updated to new documentation

CHANGES.md, src/components/InfoPanel/InfoPanel.tsx, src/resources/lang.json
This PR:
- add tooltips (incl. translation) to the toogle buttons that control the format of the metadata information in the sidebar.
=> Add tooltips to the metadata section of the sidebar

CHANGES.md, package-lock.json, package.json, src/actions/dataActions.tsx, src/actions/otherActions.tsx, src/api/getViewerState.ts, src/api/putViewerState.ts, src/components/ControlBarActions.tsx, src/connected/AppBar.tsx, src/connected/ControlBarActions.tsx, src/index.tsx, src/reducers/controlReducer.ts, src/reducers/dataReducer.ts, src/resources/config.json, src/resources/config.schema.json, src/states/persistedState.ts, src/util/baseurl.ts, src/util/branding.ts, src/version.ts
Closes #447 
The restored state includes:
See https://github.com/xcube-dev/xcube/pull/1091
=> New "share" action that creates a state permalink

src/model/dataset.ts, src/util/json.test.ts, src/util/json.ts, src/util/wms.ts
@b-yogesh in Oct 2024 you changed the `attrs` property of the `Dataset` and `Variable` interfaces to use `ReactNode`. This is not acceptable for Redux-managed state types.
In this PR I introduced `util/json.ts` to fix this.
=> Fix `Dataset` and `Variable` types

CHANGES.md, src/api/hasViewerStateApi.ts, src/config.ts
The new "share" button no longer appears if the xcube Server has no respective persistence API configuration.
Closes #470
=> Hide "share" button without persistence API

CHANGES.md, src/ext/plugin.ts
Added `Markdown` component to be used in server-side extensions. It has a single `text` property that takes the markdown text.
See related https://github.com/xcube-dev/xcube/pull/1127
=> New Markdown component for chartlets

CHANGES.md, package-lock.json, package.json, src/components/SplitPane.tsx, src/components/Splitter.tsx, src/hooks/useMouseDrag.ts, src/version.ts
Fixed a problem where mouse splitters used to resize two components (e.g., two layers in map view, or map view and side panels) created a drift while dragging.
=> Fixed drift while dragging splitter

CHANGES.md, src/components/ControlBarItem.tsx, src/components/DatasetSelect.tsx, src/connected/ControlBar.tsx
Closes: #485 
This PR adds divider between each control items to provide a visual separation to the user.
=> Add `Divider` in control bar

README.md
This PR adds documentation on how to install the local Chartlets in xcube-viewer for quicker iteration and development.
=> Add Chartlets integration documentation in README

CHANGES.md, package.json, src/actions/dataActions.tsx, src/api/getDatasets.ts, src/components/DatasetSelect.tsx, src/model/dataset.ts, src/reducers/controlReducer.ts
This PR does the following
- respects the new addition of attribute `EntrypointDatasetId` to the xcube-server config that allows the users to choose freely which dataset they want to show on xcube-viewer upon loading.
- use `sortValue` from the config provided to sort the datasets within a group that are shown in the dataset selector. The sorting happens as follows when comparing two elements:
- if both have sortValue, sort them
- if none of them have sortValue, fallback to sorting by title
- if one of them has sortValue, prefer the one with sortValue.
This provides the user with ability to sort only subset of datasets in a group if preferred to.
Issue: https://github.com/xcube-dev/xcube/issues/1135
See also: https://github.com/xcube-dev/xcube/pull/1147
=> Enable selecting initial dataset to be shown on the viewer app from config file

CHANGES.md, src/components/InfoPanel/DatasetInfoCard.tsx, src/components/InfoPanel/PlaceInfoCard.tsx, src/components/InfoPanel/VariableInfoCard.tsx, src/components/InfoPanel/common/KeyValueContent.tsx, src/components/InfoPanel/common/utils.ts
In this PR:
* Fixed application crash caused by metadata attributes that are (JSON) objects. Now attributes values of any type are rendered.
* Added a type column to the metadata attribute tables displayed in the "details" panel when in list mode.
=> Fixed rendering metadata attributes

CHANGES.md, src/connected/ColorBarLegend2.tsx, src/ext/store.ts, src/selectors/controlSelectors.tsx
This PR addresses a part of https://github.com/xcube-dev/xcube/issues/1134 by exposing two new State properties `selectedDatasetTitle` and `selectedDataset2Title`.
=> Add new State properties

CHANGES.md, package-lock.json, package.json, src/version.ts
* Slightly updated default logo image (to have a background and hence can be 
used for light and dark theme mode).
*  Pinned `vega-lite` and `vega` versions to ensure compatibility and prevent peer
dependency conflicts during installation (#531).
=> Releasing 1.6.1

src/components/UserControl.tsx
This PR:
- enables styling of the `Login` button, so that the button's appearance can be determined in the xcube Viewer configurations.
- adds tooltip to `Login` button.
- prevents the movement of the `Login` button to the left when logging in/logged in.
This PR closes #534.
=> Enable customization of `Login` button

CHANGES.md, src/actions/dataActions.tsx, src/resources/config.json, src/resources/lang.json, src/util/branding.ts
This PR:
- enables a custom permalink message with the information on exiration duration of the link in day in `config.json`s. This customization is optional.
- adds translations to `lang.json`
in `config.json`:
```
"branding": {  
"permalinkExpirationDays": 300
}
```
Example:
This PR closes #500.
=> Enable custom permalink message

src/components/Viewer/Viewer.tsx, src/components/ol/Map.tsx, src/components/ol/layer/Tile.tsx
The `Map` component can now report progress through the `onTileLoadProgress: (p: TileLoadProgress)` property (addressing #283). Current usage demo implements this handler to output progress to the console:
This should be changed to change the app state, so a progress component can reflect this.
=> Allow map to report tile load progress
